version: "2"
services:

  node-red:
    container_name: nodered
    image: nodered/node-red:1.0.6-2    
    ports:
      - 1880:1880

  kiosk-node-red:
    image: torizon/kiosk-mode-browser:$CT_TAG_KIOSK_MODE_BROWSER
    command: --browser-mode http://nodered:1880
    privileged: true
    volumes:
      - /tmp:/tmp 
      - /var/run/dbus://var/run/dbus
      - /dev/dri:/dev/dri
    depends_on:
      - node-red

