version: "2"
services:
  kiosk:
    image: torizon/kiosk-mode-browser:$TAG
    command: --browser-mode http://google.com
    privileged: true
    volumes:
      - /tmp:/tmp 
      - /var/run/dbus://var/run/dbus
      - /dev/dri:/dev/dri
