version: "2.4"
services:

  kiosk:
    image: torizon/arm32v7-debian-kiosk-mode-browser:latest
    network_mode: host
    security_opt:
      - seccomp:unconfined
    command: --window-mode http://portainer:9000
    volumes:
      - type: bind
        source: /tmp
        target: /tmp
      - type: bind
        source: /var/run/dbus
        target: /var/run/dbus
      - type: bind
        source: /dev/dri
        target: /dev/dri
    shm_size: '256mb'
    device_cgroup_rules:
      # ... for /dev/dri devices
      - 'c 226:* rmw'

  chromium:
    image: torizon/arm32v7-debian-kiosk-mode-browser:latest
    security_opt:
      - seccomp:unconfined
    command: --browser-mode https://www.google.com
    volumes:
      - type: bind
        source: /tmp
        target: /tmp
      - type: bind
        source: /var/run/dbus
        target: /var/run/dbus
      - type: bind
        source: /dev/dri
        target: /dev/dri
    shm_size: '256mb'
    device_cgroup_rules:
      # ... for /dev/dri devices
      - 'c 226:* rmw'

  shell:
    image: torizon/arm32v7-debian-shell
    container_name: shell
    stdin_open: true
    tty: true 
    command: /bin/bash

  developer-tools:
    image: torizon/arm32v7-debian-dev-tools:latest
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: /dev
        target: /dev
      - type: bind
        source: /boot
        target: /boot

  codesys:
    image: torizonextras/codesys
    privileged: true
    network_mode: host

  kiosk-codesys:
    image: torizon/arm32v7-debian-kiosk-mode-browser:latest
    command: --browser-mode http://localhost:8080
    security_opt:
      - seccomp:unconfined
    volumes:
      - type: bind
        source: /tmp
        target: /tmp
      - type: bind
        source: /var/run/dbus
        target: /var/run/dbus
      - type: bind
        source: /dev/dri
        target: /dev/dri
    depends_on:
      - codesys
    shm_size: '256mb'
    device_cgroup_rules:
      # ... for /dev/dri devices
      - 'c 226:* rmw'

  crank:
    privileged: true
    image: cranksoftware/torizon_imx6:6_1
    volumes:
      - type: bind
        source: /tmp
        target: /tmp
      - type: bind
        source: /dev
        target: /dev

