version: "2.4"
services:

  kiosk:
    image: torizon/arm64v8-debian-kiosk-mode-browser:latest
    network_mode: host
    security_opt:
      - seccomp:unconfined
    command: --window-mode http://portainer:9000
    volumes:
      - type: bind
        source: /tmp
        target: /tmp
      - type: bind
        source: /var/run/dbus
        target: /var/run/dbus

  chromium:
    image: torizon/arm64v8-debian-kiosk-mode-browser:latest
    security_opt:
      - seccomp:unconfined
    command: --browser-mode https://www.google.com
    volumes:
      - type: bind
        source: /tmp
        target: /tmp
      - type: bind
        source: /var/run/dbus
        target: /var/run/dbus

  shell:
    image: torizon/arm64v8-debian-shell
    container_name: shell
    stdin_open: true
    tty: true 
    command: /bin/bash

  developer-tools:
    image: torizon/arm64v8-debian-dev-tools:latest
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: /dev
        target: /dev
      - type: bind
        source: /boot
        target: /boot

  codesys:
    image: torizonextras/codesys
    privileged: true
    network_mode: host

  kiosk-codesys:
    image: torizon/arm64v8-debian-kiosk-mode-browser:latest
    command: --browser-mode http://localhost:8080
    security_opt:
      - seccomp:unconfined
    volumes:
      - type: bind
        source: /tmp
        target: /tmp
      - type: bind
        source: /var/run/dbus
        target: /var/run/dbus
    depends_on:
      - codesys

  crank:
    privileged: true
    image: cranksoftware/torizon_imx8:6_1
    volumes:
      - type: bind
        source: /tmp
        target: /tmp
      - type: bind
        source: /dev
        target: /dev

